### ISSUE TITLE
Make hash headers optional and default

### ISSUE THREAD

**Issue by Kunde21** [Kunde21/markdownfmt#14]
Hash and underline headers result in the same parsed structure, so we should be able to manage and generate both.   

Other parsers will default to hash headers, so I feel okay defaulting to the same (merged in #13).  
This leaves underline headers as an optional generation target.  An option flag fits here as a solution to the bike-shedding problem.

**Comment by bwplotka** [comment]
:+1:

**Comment by karelbilek** [comment]
I personally prefer underline

But I look in the source code now, and it seems like with the refactor, adding the underlines would be too much complexity for dubious benefit. (Currently, we just print ## on entering the node, which is much simpler)

I'm for simplicity :) let's keep it as hashes. (Maybe keep this as nice-to-have? I don't know)

**Comment by bwplotka** [comment]
Your PR makes sense. I am happy to make default whatever as well. Up to you (:
