### ISSUE TITLE
Control the width of markdown lines.

### ISSUE THREAD

**Issue by bwplotka** [Kunde21/markdownfmt#15]
![image](https://user-images.githubusercontent.com/6950331/97467347-035b9d80-193c-11eb-851b-0086a257e477.png)

I would love if formatter would adjust the wide with respect to words, otherwise, it's incredibly hard to read and edit docs in editors. (:

**Comment by bwplotka** [comment]
Not needed anymore - just configured IDE for it ;p

**Comment by karelbilek** [comment]
Yeah I was just thinking about this - markdownfmt HTML renderer has an option WithHardLinks, that controls if hardlinks are  "preserved" or not.

Actually we might want to reopen this, or at least have the ability to set up markdownfmt to preserve the newlines.

```
a
b
```

is rendered, according to CommonMark, as 

```
<p>a
b</p>
```

or, with hardlinks preserved, as

```
<p>a<br>
b</b>
```

So the newlines are not meaningless and we should not put them back - or at least have option for that.

**Comment by karelbilek** [comment]
I will probably open another issue as this is not *exactly* what you wanted

**Comment by bwplotka** [comment]
agree, it's bit different
