### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by bwplotka** [Kunde21/markdownfmt#18]

**Comment by karelbilek** [comment]
I would not set travis in 2021. :D

Github has some built-in CI? I never used it

**Comment by karelbilek** [comment]
Well, that was easy.

https://github.com/Kunde21/markdownfmt/commit/08404f16ba4902302305a2800bb87e5f9d9fe27a

**Comment by bwplotka** [comment]
❤️

**Comment by bwplotka** [comment]
That was easy but.... we could go even further: https://github.com/Kunde21/markdownfmt/issues/30
