### ISSUE TITLE
Wrong formatting of code blocks (wrong whitespaces)

### ISSUE THREAD

**Issue by bwplotka** [Kunde21/markdownfmt#20]
See repro: https://github.com/bwplotka/markdownfmt/pull/1

Root cause is in goldmark parser: https://github.com/yuin/goldmark/issues/177

**Comment by karelbilek** [comment]
The second tab root cause is fixed here, waiting for review :(

https://github.com/yuin/goldmark/pull/187

Not sure if it fixes the first one, I think that is actually different thing

**Comment by bwplotka** [comment]
Thank you! Not a blocker (:

**Comment by karelbilek** [comment]
Finally fixed :D sorry for being few months late
