### ISSUE TITLE
please add missing LICENSE file to make e.g. pkg.go.dev work

### ISSUE THREAD

**Issue by stapelberg** [Kunde21/markdownfmt#24]
The README says this repository is licensed under the MIT license, but you don’t have a LICENSE file committed.

Without the LICENSE file, GitHub cannot display which license is used.

Worse, pkg.go.dev will not show documentation for packages whose license cannot be determined: https://pkg.go.dev/github.com/Kunde21/markdownfmt/v2

Could you commit a LICENSE file please?

**Comment by Kunde21** [comment]
Created with MIT template.  Thank You
