### ISSUE TITLE
Detach the fork

### ISSUE THREAD

**Issue by abhinav** [Kunde21/markdownfmt#48]
Seeing as this variant of markdownfmt is maintained independently of the [original blackfriday-based version](https://github.com/shurcooL/markdownfmt) and as far as I can tell, there are no plans to merge this work back, we should consider detaching the fork. This will get rid of the "forked from" message at the top of the page, and the following message in the tree browser:

> This branch is 43 commits ahead, 13 commits behind shurcooL:master.

The process for doing this is slightly manual; it's documented at https://ralphjsmit.com/unfork-github-repo.

**Comment by Kunde21** [comment]
Done.  Thank you.
